spring:
  application:
    name: MyBoardProject

  datasource:
    url: jdbc:mysql://localhost:3306/exampledb
    username: jongwoolee
    password: jong1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  server:
    port: 8080